# Import image with tag version 3.12
FROM python:3.12.1-alpine

# Custom workdir to save all project
WORKDIR /openseries

# Copy all local project to inside image
COPY . .

# Install requirement
RUN pip install -r requirements.txt

# Install dev-requirements
RUN pip install -r dev-requirements.txt

# Running pytest
CMD ["pytest"]
